# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d689f7e491ada9c6c9ed1d781041f772f7b9accef1cc303c0352572f3ac6c95e36e46bb59d5eff741bc3de9e4c67cf2aecec0a29ff9d9eb500cf03ff19225da

test:
  secret_key_base: 538f7a31c05721735cdf45116629a9def6a3f6eeabb9a525e9d1ebb56c0d110fe79ece0e0a1d08b80b61716e87504754635aa9702d541de63e21cc89642f5279

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
